window.DA_LANG = window.DA_LANG || {};
window.DA_LANG.en = {
  "researchDatabase": "RESEARCH DATABASE",
  "navSubject": "Subject file",
  "navZandik": "Zandik",
  "navSegments": "Segments",
  "navTimeline": "Timeline",
  "navAnalysis": "Analysis",
  "navArchive": "Archive",
  "navAudio": "Audio logs",
  "archiveOnline": "ARCHIVE ONLINE",
  "archiveCompletion": "Archive completion",
  "recordsInaccessible": "Some records remain inaccessible.",
  "accessLevel": "ACCESS LEVEL · RESEARCHER",
  "breadcrumbArchive": "DOTTORE ARCHIVE",
  "confidential": "CONFIDENTIAL",
  "file02": "FILE 02",
  "primarySubject": "PRIMARY SUBJECT",
  "heroLead": "Central archive file containing official appearances, early records, Segment material, chronology, and research notes.",
  "designation": "Designation",
  "affiliation": "Affiliation",
  "archiveStatus": "Archive status",
  "active": "Active",
  "access": "Access",
  "restricted": "Restricted",
  "openSegments": "Open segment registry",
  "viewTimeline": "View chronology",
  "subjectVisual": "SUBJECT VISUAL",
  "primeFile": "02 / PRIME FILE",
  "officialPrimary": "OFFICIAL ART / PRIMARY SUBJECT",
  "imageSource": "Image source:",
  "officialArt": "official art",
  "statusLabel": "Status:",
  "assigned": "assigned",
  "earlyRecords": "EARLY RECORDS",
  "zandikText": "The earlier layer of the archive: Akademiya records, expedition fragments, documents, and material related to Zandik before the fully formed Harbinger persona.",
  "archived": "ARCHIVED",
  "academiyaPeriod": "AKADEMIYA PERIOD",
  "officialArtCaps": "OFFICIAL ART",
  "earlyRecord": "EARLY RECORD",
  "researchForm": "RESEARCH FORM",
  "recordAcademiyaTitle": "Akademiya",
  "recordAcademiyaText": "The name Zandik appears in material connected with the Sumeru Akademiya. In this archive, those records serve as the starting point for Dottore’s history before his role as a Harbinger.",
  "recordExpeditionTitle": "Expedition material",
  "recordExpeditionText": "Field records connect him with the study of ruins, ancient mechanisms, and knowledge that moved beyond conventional academic limits.",
  "recordMethodsTitle": "Research methods",
  "recordMethodsText": "Even the early material shows a persistent interest in experiments that others regarded as dangerous or unacceptable. For the archive, this is one of the lines connecting Zandik with the later Dottore.",
  "recordTransitionTitle": "Zandik and Dottore",
  "recordTransitionText": "Zandik is the real name of the original human whose age-based versions became the Segments. Later canon also shows that Segment 35 preferred the name \"Dottore\", reserving \"Zandik\" for the original. What remains less explicit is not their connection, but the exact point at which Zandik fully assumed the Harbinger role and codename.",
  "observerNote": "OBSERVATION · NAHIDA · STYLIZED ENTRY",
  "nahidaObservation": "\"He treats knowledge as though no boundary deserves to be final. When speaking with him, it is especially important to remember that curiosity is not only his way of understanding the world, but also a reason to test how far one can go.\"",
  "observerDisclaimer": "Not a direct in-game quote; a stylized archive observation based on the character’s established portrayal.",
  "interpretiveNote": "OBSERVATION",
  "instanceRegistry": "INSTANCE REGISTRY",
  "interactiveModule": "INTERACTIVE MODULE",
  "instanceSelected": "INSTANCE SELECTED",
  "statusCaps": "STATUS",
  "dataCaps": "DATA",
  "canonSlot": "CANON PROFILE",
  "webttoreKicker": "SEPARATE VISUAL RECORD",
  "webttoreText": "\"Webttore\" is a fan label for the version of Dottore depicted in the official Genshin Impact manga. The archive keeps this depiction separate from the numbered Segments: the image is officially published, but its exact place within the later Segment system is not explicitly established.",
  "webttoreNote": "\"Webttore\" is not an in-game name and is used here only as a convenient archive label.",
  "webttoreAlt": "Official depiction of Dottore from the Genshin Impact manga",
  "officialComicArt": "OFFICIAL MANGA",
  "sourceOfficialMangaShort": "SOURCE · OFFICIAL MANGA",
  "segmentIdentityUnknown": "SEGMENT ID · NOT ESTABLISHED",
  "chronologicalIndex": "CHRONOLOGICAL INDEX",
  "timelineHeading": "TIMELINE",
  "canonOnly": "CANON ONLY",
  "timelineNote": "The order follows the world’s internal chronology. Where canon gives no exact date, the archive does not invent one. Only events directly supported by in-game text, the official manga, item descriptions, and official HoYoverse material are included; fan retellings and theories are excluded.",
  "timelineChildhoodTitle": "Childhood · driven from his hometown",
  "timelineChildhoodText": "In a memory of Zandik’s early years, people from his hometown pursue the young boy with clubs and pitchforks, forcing him to flee. The available canon does not state why they were hostile to him, so the archive does not supply a reason.",
  "sourceGameMemory": "Source · in-game memory · reason unknown",
  "timelineAcademiyaTitle": "Zandik · Sumeru Akademiya",
  "timelineAcademiyaText": "Early field records connect Zandik with the Akademiya, expeditions, and the study of ancient mechanisms. These documents show his interest in technologies that exceeded ordinary academic practice.",
  "timelineRecruitTitle": "Exile and the Fatui",
  "timelineRecruitText": "After his break with the Akademiya, Zandik enters the Fatui. The artifact \"Wise Doctor’s Pinion\" connects his path with Pierro, who offers him a place where his research would no longer be constrained by his former limits.",
  "timelineTatarasunaTitle": "Tatarasuna · \"Escher\"",
  "timelineTatarasunaText": "Several centuries before the main story, Dottore operates in Inazuma under the identity of the mechanic Escher. The Tatarasuna incident becomes part of Kabukimono’s history and is later revealed to the Traveler through recovered memories.",
  "timelineSegmentsTitle": "Scaramouche research and the Segments",
  "timelineSegmentsText": "After Kabukimono joins the Fatui, Dottore studies his artificial body for more than a decade. Wanderer’s character story links this research to the technological basis of the Segments, while later material additionally states that Zandik turned to Khaenri’ahn technology when creating them. The archive therefore does not reduce the Segments’ origin to a single source.",
  "timelineMangaTitle": "Mondstadt · official manga",
  "timelineMangaText": "Before the Traveler’s arrival, Dottore appears in Mondstadt as a Fatui representative. The manga depicts his experiments, his treatment of subordinates, and his interest in unusual human \"specimens\".",
  "timelineSumeruTitle": "Sumeru · the new god project",
  "timelineSumeruText": "In Sumeru’s main story, Dottore cooperates with the Akademiya sages in the project to transform Scaramouche into an artificial god. After the project fails, he personally negotiates with Nahida: the bargain leaves him with both Gnoses, while her condition forces him to destroy his remaining Segments.",
  "timelineNodKraiTitle": "Nod-Krai · lunar experiment",
  "timelineNodKraiText": "Later, Dottore intervenes in the events of Nod-Krai surrounding Columbina and the power of the moons. He creates his own system, harnesses lunar forces, and enters direct conflict with the Traveler and their allies.",
  "timelineTrueMoonTitle": "\"True Moon\" · confrontation in Nod-Krai",
  "timelineTrueMoonText": "In the \"True Moon\" act, the conflict with Dottore reaches a culmination around Nod-Krai’s lunar power. The Traveler and their allies confront the system he created directly; the archive records this as a distinct stage of the conflict without inferring the Doctor’s final fate from this scene alone.",
  "timelinePuranaTitle": "Irminsul · \"Truth Amongst the Pages of Purana\"",
  "timelinePuranaText": "In Luna VII, Segment 35 carries his experiment into its final stage by binding his existence to Irminsul. The challenge description explicitly states that he casts off the constraints of corporeal form and merges with Irminsul. In the final confrontation, his manifestation perishes together with the burning Irminsul. For the archive, this is the current confirmed endpoint of Segment 35 – without speculating about a possible return.",
  "sourceGameRecords": "Source · in-game records",
  "sourceArtifact": "Source · artifact description",
  "sourceArchonQuest": "Source · Archon Quest",
  "sourceCharacterStory": "Source · character story",
  "sourceManga": "Source · official manga",
  "sourceArchonQuest32": "Source · Chapter III Archon Quests",
  "sourceWelkinMoon": "Source · Song of the Welkin Moon",
  "sourceTrueMoon": "Source · \"True Moon\" Archon Quest",
  "sourcePurana": "Source · Luna VII + Dottore challenge",
  "researchNotes": "RESEARCH NOTES",
  "characterAnalysis": "CHARACTER ANALYSIS",
  "interpretation": "CANON / INTERPRETATION",
  "analysisIntro": "Canon and interpretation are deliberately separated: factual entries rely on official material, while inferences, theories, and hypothetical scenes are labeled independently. If a summary article and a primary text allow different readings, the in-game record, dialogue, or official manga takes priority.",
  "canonLabel": "CANON",
  "inferenceLabel": "INFERENCE",
  "theoryLabel": "THEORY",
  "fitLabel": "CHARACTER-FIT",
  "worldviewBehaviorTitle": "Worldview and behavior",
  "coreProfile": "CORE PROFILE / 01",
  "humanSystemTitle": "The human as a modifiable system",
  "humanSystemText": "In \"Wise Doctor’s Pinion\", the researcher treats the human body as a system that can be improved and formulates the idea of \"enhanced humans\". This aligns with his later goal of raising humanity toward a level others would regard as divine.",
  "sourceWiseDoctor": "Source · \"Wise Doctor’s Pinion\"",
  "limitsTitle": "Limits as a technical problem",
  "limitsText": "A recurring logic runs through his projects: the limits of the body, consciousness, and even divinity are not treated as sacred. To Dottore, they function more like system parameters that can be tested, altered, or reproduced.",
  "basisRepeatedProjects": "Basis · recurring canonical projects",
  "controlTitle": "Restraint in negotiation",
  "controlText": "During his negotiation with Nahida, he remains businesslike even when the price of the bargain is the destruction of his remaining Segments. The event itself is canon; the broader inference about emotional restraint comes from how he weighs risk, information, and gain instead of immediately derailing the deal.",
  "sourceSumeruActV": "Source · Chapter III, Act V",
  "relationshipsTitle": "Relationships",
  "relationIndex": "RELATION INDEX / 02",
  "relPierroTitle": "Resources instead of restrictions",
  "relPierroText": "Pierro is tied to Zandik’s early transition into the Fatui: he offers an environment and resources where the research can continue beyond the old academic limits. It reads more as mutually useful recognition of potential than a \"rescue\".",
  "relPantaloneTitle": "A long contract and mutual dependence",
  "relPantaloneText": "\"Anomalous Tree Marrow\" records Pantalone as Dottore’s long-term patient and experimental subject: different Segments maintain his medical records across centuries, while the immortality elixir alters his aging. Later story material presents their bond as an exceptionally long collaboration combining funding, medicine, and personal history.",
  "sourcePantalone": "Source · \"Anomalous Tree Marrow\" + \"Truth Amongst the Pages of Purana\"",
  "relNahidaTitle": "An opponent he has to account for",
  "relNahidaText": "Nahida does not become a simple research object: she forces him to pay with his Segments for the bargain. Dottore, in turn, does not derail the negotiation, but converts the conflict into an exchange and leaves with both Gnoses.",
  "relWandererTitle": "Subject, prototype, and personal enemy",
  "relWandererText": "Research on Kabukimono’s artificial body gave Dottore the foundation for Segment technology. For Wanderer, that history remains intensely personal: his own lines show open hatred toward the Doctor and his copies.",
  "sourceWandererStory": "Source · Wanderer story and voice-overs",
  "relColumbinaTitle": "Closeness that becomes access",
  "relColumbinaText": "Columbina says Dottore once cared for her and even thought of her as a sister, but that the closer someone was to him, the more freely he used them. Importantly, she says he genuinely regarded such mutual \"endurance\" as part of family closeness.",
  "sourceColumbinaVO": "Source · Columbina voice-over about The Doctor",
  "relArlecchinoTitle": "A break with the old House’s practices",
  "relArlecchinoText": "Under Crucabena, permanently injured House of the Hearth children were handed over to the Doctor for experimentation. Arlecchino’s own line about the Doctor separately confirms that he proposed new cooperation plans after she took over. The archive keeps these two facts distinct and does not attribute the old House’s practices to the current Arlecchino.",
  "sourceArlecchinoVO": "Source · Arlecchino voice-over about The Doctor",
  "relColleiTitle": "Trauma left by experimentation",
  "relColleiText": "Collei’s history connects her supposed \"treatment\" to Fatui human experimentation carried out under the Doctor’s name. The official manga also shows that some procedures are performed by his subordinates, so the archive does not attribute every act of the project to Dottore personally.",
  "sourceColleiManga": "Source · Collei voice-over + official manga",
  "relTravelerTitle": "An exception he wants to keep within reach",
  "relTravelerText": "In Nod-Krai, Dottore treats the Traveler both as an exceptional subject of observation and as a potential collaborator. He isolates and studies them, discusses their unusual nature as a Descender, and repeatedly invites them to join him. Canon supports the special interest and his attempts to keep the Traveler inside his own project; it does not by itself establish emotional possessiveness.",
  "sourceTravelerDottore": "Source · Luna IV + \"True Moon\" Archon Quests",
  "theoriesTitle": "Theories and cautious inferences",
  "theoryIndex": "HYPOTHESIS SET / 03",
  "selfObjectTitle": "His own research subject",
  "selfObjectText": "Creating Segments from age-based versions of himself already turns his own identity into experimental material. The theory lies not in the Segments’ existence, but in the interpretation: Dottore appears to apply the same objectifying research logic to himself that he applies to others.",
  "rejectionTitle": "Rejection as reinforcement",
  "rejectionText": "Exile and earlier rejection may have reinforced his belief that social and ethical limits obstruct research. Canon does not establish a direct causal chain from rejection to worldview, however, so this remains only a possible amplifier of attitudes that were already present.",
  "familyTitle": "A distorted model of closeness",
  "familyText": "Columbina’s words suggest a model in which someone considered \"his own\" receives greater access to Dottore, but is also expected to endure more, remain useful, and accept the cost of his experiments. Care and instrumental use can coexist in that model.",
  "stagnationTitle": "Resistance to finality",
  "stagnationText": "From preserving versions of himself at different ages to manufacturing an artificial god, he repeatedly refuses to treat the world’s current state as final. Stagnation may be less acceptable to him than risk.",
  "characterFitTitle": "Moments that fit his established character",
  "simulationIndex": "BEHAVIOR SIMULATION / 04",
  "fitDisclaimer": "These situations are not canon. They are behavior forecasts built from recurring canonical patterns.",
  "fitAttentionTitle": "Attention without tenderness",
  "fitAttentionText": "He could easily remember another person’s habits, measurements, and tiny reactions simply because he observes closely. Attention by itself does not imply empathy.",
  "fitProvocationTitle": "Controlled provocation",
  "fitProvocationText": "A calm, almost polite provocation fits him better: say exactly enough to trigger a useful reaction and observe it, rather than raising his voice merely to intimidate.",
  "fitPossessionTitle": "Control shading into possessiveness",
  "fitPossessionText": "Possessiveness is never named as a distinct canonical trait, but a logic of \"what is valuable should remain within my access\" fits him well. With the Traveler, he already moves beyond observation and repeatedly tries to draw them to his side. In a closer bond, this could plausibly appear less as jealousy and more as control over conditions, information, risks, and other people’s access to someone he considers exceptional or \"his\".",
  "basisTravelerInterest": "Basis · canonical interest in the Traveler + recurring control pattern",
  "fitEqualTitle": "A valuable opponent",
  "fitEqualText": "If someone possesses unique knowledge or power and remains more useful alive, testing them, talking, or bargaining fits Dottore’s shown pattern well. It does not imply that he would necessarily spare the source once that value is gone.",
  "fitCareTitle": "\"Care\" through utility",
  "fitCareText": "If affection were to show, expressing it through resources, treatment, access to knowledge, or practical help is more plausible than direct emotional reassurance. Canon involving Columbina and Pantalone makes this model possible, but not universal.",
  "fitFailureTitle": "Defeat as another experiment",
  "fitFailureText": "After failure, he is more likely to record variables, identify a useful anomaly, and redesign the next attempt. Irritation is possible, but it need not erase his research interest.",
  "oocMarker": "LESS SUPPORTED",
  "oocTitle": "What canon supports less strongly",
  "oocOne": "Cruelty performed purely for spectacle is less strongly supported than his recurring instrumental cruelty – but canon does not make it impossible.",
  "oocTwo": "Open sentimentality without context is weakly supported; closeness is more often shown through actions, habits, agreements, and practical value.",
  "oocThree": "Abandoning a central goal solely out of pity is not supported by his shown decisions so far, though new circumstances could theoretically change his priorities.",
  "oocFour": "A minor jab at his ego may provoke irritation or sarcasm, but immediate loss of composure is less supported than a calculated response.",
  "evidenceStorage": "EVIDENCE STORAGE",
  "filesImagesText": "FILES / IMAGES / TEXT",
  "documents": "Documents",
  "documentsText": "Records and texts",
  "gallery": "Gallery",
  "galleryText": "Official images",
  "voiceLines": "Voice lines",
  "voiceLinesText": "Lines and quotations",
  "symbols": "Symbols",
  "symbolsText": "Signatures and scripts",
  "audioDatabase": "AUDIO DATABASE",
  "audioLogs": "AUDIO LOGS",
  "noTrackLoaded": "NO TRACK LOADED",
  "laboratoryAmbience": "Laboratory ambience",
  "placeholderTrack": "Placeholder track · add your audio later",
  "footerDraft": "SUBJECT II ARCHIVE · DRAFT 13",
  "footerUnavailable": "Some data intentionally unavailable.",
  "section.overview": "SUBJECT FILE",
  "section.zandik": "ZANDIK",
  "section.segments": "SEGMENTS",
  "section.timeline": "TIMELINE",
  "section.analysis": "ANALYSIS",
  "section.archive": "ARCHIVE",
  "section.audio": "AUDIO LOGS",
  "language.selected": "SET",
  "language.triggerTitle": "Language / Script",
  "language.triggerAria": "Language and script mode. Selected: {code}",
  "aria.openMenu": "Open menu",
  "aria.textSize": "Reading text size",
  "toast.signalInterference": "SIGNAL INTERFERENCE DETECTED",
  "toast.researchEnhanced": "RESEARCH MODE: ENHANCED",
  "toast.researchStandard": "RESEARCH MODE: STANDARD",
  "media.recordLabel": "AUDIOVISUAL RECORD",
  "media.credit": "Genshin Impact · Official YouTube · {year}",
  "segment.8.alt": "Official art of Segment 08",
  "segment.8.status": "ARCHIVED",
  "segment.8.text": "The earliest iteration shown here: a youthful appearance with an uncovered face and little of the visual distance later associated with the researcher.",
  "segment.18.alt": "Official art of Segment 18",
  "segment.18.status": "ARCHIVED",
  "segment.18.text": "A young transitional iteration. The features grow sharper and the presentation more composed, already pointing toward the later research-oriented aesthetic.",
  "segment.25.alt": "Official art of Segment 25",
  "segment.25.status": "ARCHIVED",
  "segment.25.text": "An early adult iteration in which the scientist persona becomes especially prominent: restrained presentation, a protective mask, and a stronger laboratory aesthetic.",
  "segment.35.alt": "Official art of Segment 35",
  "segment.35.status": "ARCHIVED",
  "segment.35.text": "The 35-year-old Segment, known as the Omega Build, is Dottore’s most recognizable story incarnation: this is the iteration encountered in Sumeru, and the one who bargains with Nahida and destroys the other Segments then in existence. Later story material continues Segment 35’s line, making him Dottore’s primary on-screen \"face\".",
  "segment.45.alt": "Official art of Segment 45",
  "segment.45.status": "ARCHIVED",
  "segment.45.text": "A later iteration with a heavier, more imposing silhouette. Fur trim and layered clothing reinforce a sense of distance and authority.",
  "segment.65.alt": "Official art of Segment 65",
  "segment.65.status": "ARCHIVED",
  "segment.65.text": "A late iteration with the darkest presentation: the plague-like mask and dark clothing turn the silhouette into an almost emblematic image of the archive and its forbidden research.",
  "media.lazzo.title": "A Winter Night's Lazzo",
  "media.lazzo.description": "Official teaser featuring Dottore’s voiced appearance among the Fatui Harbingers.",
  "media.v31.title": "King Deshret and the Three Magi",
  "media.v31.description": "Official Version 3.1 trailer: early voiced Dottore material from the Sumeru arc.",
  "media.v32.title": "Akasha Pulses, the Kalpa Flame Rises",
  "media.v32.description": "Official Version 3.2 trailer tied to the climax of the artificial-god project in Sumeru.",
  "media.luna4.title": "A Traveler on a Winter's Night",
  "media.luna4.description": "Later official voiced material continuing Dottore’s storyline in Nod-Krai.",
  "media.luna7.title": "Truth Amongst the Pages of Purana",
  "media.luna7.description": "Official Luna VII trailer, again listing Dottore among the voiced characters.",
  "sidebar.span.1": "TEXT SIZE",
  "sidebar.contactTitle": "UPDATES & CONTACT",
  "sidebar.contactDescription": "Follow project updates or send feedback, corrections and suggestions privately.",
  "header.language-group-title.1": "LANGUAGES",
  "header.language-group-title.2": "SCRIPT MODE",
  "header.language-option-name.1": "Future script",
  "header.language-popover-foot.1": "Teyvat Script uses English text as its base. Additional numerals and punctuation are a stylistic project extension.",
  "timeline.h4.1": "Childhood · driven from his home village",
  "timeline.p.1": "In a memory of his early years, the young Zandik is chased from his home village by residents carrying clubs and pitchforks. The available canon does not state why they were hostile, so the archive does not fill in the reason.",
  "timeline.timeline-source.1": "Source · in-game memory · reason unknown",
  "timeline.h4.2": "Zandik · Sumeru Akademiya",
  "timeline.p.2": "Early field records connect Zandik with the Akademiya, expeditions, and the study of ancient mechanisms. These documents show an interest in technology that exceeded ordinary academic practice.",
  "timeline.timeline-source.2": "Source · in-game records",
  "timeline.h4.3": "Expulsion and the Fatui",
  "timeline.p.3": "After his break with the Akademiya, Zandik enters the Fatui. \"Wise Doctor’s Pinion\" connects this transition with Pierro, who offers an environment and resources where his research is no longer constrained by his former academic framework.",
  "timeline.timeline-source.3": "Source · \"Wise Doctor’s Pinion\"",
  "timeline.h4.4": "Tatarasuna · \"Escher\"",
  "timeline.p.4": "Several centuries before the main story, Dottore operates in Inazuma under the identity of the mechanic Escher. The Tatarasuna incident becomes part of Kabukimono’s history and is later revealed to the Traveler through memories.",
  "timeline.timeline-source.4": "Source · Archon Quest",
  "timeline.h4.5": "Scaramouche research and the Segments",
  "timeline.p.5": "After Kabukimono joins the Fatui, Dottore studies his artificial body for more than a decade. Wanderer’s story connects that research to the technological basis of the Segments; Segment 35’s later account also says Zandik turned to Khaenri’ahn technology when creating them. The archive therefore does not reduce their origin to a single source.",
  "timeline.timeline-source.5": "Source · Wanderer story + Segment 35’s later account",
  "timeline.h4.6": "Pantalone · resources, medicine, and longevity",
  "timeline.p.6": "During his Fatui years, Zandik’s connection with Pantalone develops into a long-term exchange: Pantalone funds research, while Zandik and later his Segments provide medical treatment and work on the immortality elixir. Medical records trace this arrangement across centuries.",
  "timeline.timeline-source.6": "Source · \"Anomalous Tree Marrow\" + \"Truth Amongst the Pages of Purana\"",
  "timeline.h4.7": "Age 85 · the original Zandik dies",
  "timeline.p.7": "Attempts to extend his life do not make the original Zandik immortal. On the morning he turns eighty-five, he dies while the Segments consciously refrain from helping and treat the event as a rare opportunity to study their own body. Afterward, they perform an autopsy and record the results.",
  "timeline.timeline-source.7": "Source · \"Truth Amongst the Pages of Purana\" + \"Anomalous Tree Marrow II\"",
  "timeline.h4.8": "Mondstadt · official manga",
  "timeline.p.8": "Before the Traveler arrives, Dottore appears in Mondstadt as a Fatui representative. The manga shows his experiments, his treatment of subordinates, and his interest in unusual human \"specimens\". The exact correspondence of this version to the later numbered Segment system is not explicitly established.",
  "timeline.timeline-source.8": "Source · official manga",
  "timeline.h4.9": "Sumeru · the new god project",
  "timeline.p.9": "During Sumeru’s main story, Dottore works with the Akademiya sages on the project to turn Scaramouche into an artificial god. After the project fails, he personally negotiates with Nahida: the bargain gives him both Gnoses, while her price requires him to destroy his remaining Segments.",
  "timeline.timeline-source.9": "Source · Chapter III Archon Quests",
  "timeline.h4.10": "Nod-Krai · lunar experiment",
  "timeline.p.10": "In Nod-Krai, Dottore uses lunar authority and builds a system of prohibitions that temporarily forces opponents to obey rules of his making. The experiment directly continues his interest in overcoming laws he regards as imposed upon the world.",
  "timeline.timeline-source.10": "Source · \"Song of the Welkin Moon\" + challenge description",
  "timeline.h4.11": "Nod-Krai · defeat of the lunar manifestation",
  "timeline.p.11": "Dottore’s lunar manifestation is defeated. Later, Segment 35 explicitly tells Pantalone that he still obtained the information he wanted from the process. The archive therefore records this as the loss of a particular body or manifestation, not as proof that the entire identity was erased.",
  "timeline.timeline-source.11": "Source · Nod-Krai + \"Truth Amongst the Pages of Purana\"",
  "timeline.h4.12": "Irminsul · \"Truth Amongst the Pages of Purana\"",
  "timeline.p.12": "Under his arrangement with Dottore, Pantalone places the Doctor’s final data backup into the Ley Lines. Segment 35 then casts off the constraints of physical form and merges with Irminsul, continuing the experiment from within. His visible manifestation disappears when Irminsul burns, while the records preserve digitized memories. Canon confirms those data and the loss of the manifestation, but by itself proves neither permanent annihilation nor a return.",
  "timeline.timeline-source.12": "Source · Luna VII + \"Anomalous Tree Marrow III\" + challenge description",
  "analysis.analysis-chip.1": "CANON",
  "analysis.h5.1": "A \"new world\", not simple godhood",
  "analysis.p.1": "Later dialogue and descriptions frame his goal as broader than personal ascension. Dottore connects the existing order with the laws of Life, Death, Time, and Space, which he treats as constraints, while his \"new world\" is tied to escaping imposed rules. His own elevation to godhood is explicitly described as only one of his experiments.",
  "analysis.analysis-source.1": "Source · later quests + Heretic of the False Moon / Exalted Master descriptions",
  "analysis.analysis-chip.2": "CANON",
  "analysis.h5.2": "Uniqueness against repetition",
  "analysis.p.2": "Segment 35 directly criticizes the premise of the Segments: if every copy is equally \"him\", none has an exclusive claim to being \"him\". He also treats a soul fixed at one point in age as simultaneously complete and restrictive. The conflict of identity is therefore part of the canonical material, not only a fan inference.",
  "analysis.analysis-source.2": "Source · \"Truth Amongst the Pages of Purana\" + \"Anomalous Tree Marrow II\"",
  "analysis.analysis-chip.3": "CANON",
  "analysis.h5.3": "The soul as transferable information",
  "analysis.p.3": "Later material shows research into splitting and transferring souls, transmission channels, and the digitization of memories. Dottore’s plan uses both death as a route for part of the soul to enter the Ley Lines and a separate data backup. In this system, death becomes not only an ending but also a technical boundary of the experiment.",
  "analysis.analysis-source.3": "Source · \"Anomalous Tree Marrow III\" + \"Truth Amongst the Pages of Purana\"",
  "analysis.h5.4": "Centuries of exchange: resources, medicine, and trust",
  "analysis.p.4": "Medical records trace their connection from early treatment into centuries of collaboration: Pantalone funds research, while Dottore and his Segments sustain his treatment and the immortality-elixir program. In a later conversation, Dottore addresses him as \"my dear friend\" and calls mutual interest the foundation of the most reliable relationships. This supports long personal familiarity and trust beyond a transaction, but the archive does not treat one form of address as proof of unambiguous emotional intimacy.",
  "analysis.analysis-source.4": "Source · \"Anomalous Tree Marrow\" + \"Truth Amongst the Pages of Purana\"",
  "analysis.analysis-chip.4": "THEORY",
  "analysis.h5.5": "Death as a transition toward reconstruction",
  "analysis.p.5": "Canon confirms preparations to split the soul, move it through the Ley Lines, and preserve memories as data. Building on that material, Illustrious-Snake proposes that Dottore’s successive \"deaths\" may have been not only defeats, but stages in a prepared reconstruction of identity. There is currently no confirmation that he actually returned after the final event.",
  "analysis.span.1": "Community theory · Illustrious-Snake",
  "analysis.span.2": "original analysis ↗",
  "analysis.analysis-chip.5": "THEORY",
  "analysis.h5.6": "A third fragment and the \"lizard anchor\" hypothesis",
  "analysis.p.6": "A more speculative branch of the same theory proposes that the soul may have been divided into more than the two explicitly stated parts, with the recurring lizard serving as a vessel or external anchor. The idea draws parallels with experiments involving human souls transferred into animals and the lizard’s visual appearances around important events. No canonical line directly identifies the animal as Dottore, so this hypothesis remains highly speculative.",
  "analysis.span.3": "Community theory · Illustrious-Snake",
  "analysis.span.4": "original analysis ↗",
  "archive.tag.1": "OFFICIAL EXTERNAL SOURCES",
  "archive.archive-intro.1": "This section stores links to publicly available official material rather than copies of media files. Previews are loaded from external sources, keeping the archive lightweight without storing video or audio on the device.",
  "archive.lore-index-kicker.1": "IN-GAME LORE INDEX",
  "archive.h4.1": "Records & Items",
  "archive.lore-index-count.1": "06 RECORDS",
  "archive.lore-index-intro.1": "A catalogue of primary in-game material related to Dottore. Rather than reproducing full texts, each archive card records where the source appears, what it establishes, and why it matters to the character study.",
  "archive.lore-source-chip.1": "TYPE · QUEST ITEM",
  "archive.lore-source-chip.2": "SOURCE · TROUNCE DOMAIN",
  "archive.lore-source-chip.3": "BINDING FIELD OF UNIVERSAL NIRVANA",
  "archive.lore-source-chip.4": "LUNA VII",
  "archive.lore-record-code.1": "RECORD · ATM-I",
  "archive.h5.1": "Anomalous Tree Marrow I",
  "archive.lore-record-summary.1": "Experimental and medical records linking the early Zandik to Feofan Sergeyevich Veksel and tracing the subject's later history as Pantalone.",
  "archive.lore-record-tag.1": "Pantalone",
  "archive.lore-record-tag.2": "Medicine",
  "archive.lore-record-tag.3": "Immortality",
  "archive.lore-record-label.1": "ARCHIVE NOTE",
  "archive.p.1": "The record begins as an acute-toxicity experiment report. The third specimen's data is transferred to a separate file under the name Feofan Sergeyevich Veksel. Later entries document medical care, the appearance of the Regrator designation, anti-aging trials, and centuries of treatment performed by different Segments.",
  "archive.lore-record-label.2": "KEY DATA",
  "archive.lore-record-fact.1": "Feofan first appears as a 20-year-old specimen whose records are removed from the general toxicity report.",
  "archive.lore-record-fact.2": "The file later receives the Regrator designation and continues across centuries.",
  "archive.lore-record-fact.3": "The record shows Zandik and Segments 8, 18, 25, 35, 45, and 65 participating in medical and experimental procedures.",
  "archive.lore-record-code.2": "RECORD · ATM-II",
  "archive.h5.2": "Anomalous Tree Marrow II",
  "archive.lore-record-summary.2": "Dialogue between the original Zandik and six Segments: everyday disputes, funding, identity, and their response to the original's death.",
  "archive.lore-record-tag.4": "Segments",
  "archive.lore-record-tag.5": "Identity",
  "archive.lore-record-tag.6": "Zandik",
  "archive.lore-record-label.3": "ARCHIVE NOTE",
  "archive.p.2": "One of the most direct records of the Segments' internal dynamics. Zandik and versions 8, 18, 25, 35, 45, and 65 discuss work, funding, and which of them can meaningfully be called \"me\"; after the original Zandik dies, the conversation turns to his autopsy and further research.",
  "archive.lore-record-label.4": "KEY DATA",
  "archive.lore-record-fact.4": "The record directly presents age-versions 8, 18, 25, 35, 45, and 65 together.",
  "archive.lore-record-fact.5": "35 explicitly distinguishes the original Zandik from the Segments, then questions the idea of any single authentic \"me\".",
  "archive.lore-record-fact.6": "After the original's death, the Segments immediately treat his body as a source of autopsy data and future pharmaceutical research.",
  "archive.lore-record-code.3": "RECORD · ATM-III",
  "archive.h5.3": "Anomalous Tree Marrow III",
  "archive.lore-record-summary.3": "Research into soul division, transfer mechanisms, animal experiments, and the digitization of memory through the Ley Lines.",
  "archive.lore-record-tag.7": "Soul",
  "archive.lore-record-tag.8": "Digitization",
  "archive.lore-record-tag.9": "Ley Lines",
  "archive.lore-record-label.5": "ARCHIVE NOTE",
  "archive.p.3": "The record documents the next stage of research: Dottore considers not only dividing a soul, but delivering it to a designated destination. He proposes animal experiments using other people's souls, records the second phase of transfer research, and arrives at digitization as a means of preserving memory.",
  "archive.lore-record-label.6": "KEY DATA",
  "archive.lore-record-fact.7": "Soul division is treated as a manageable problem; the main obstacle shifts to the transfer channel and destination.",
  "archive.lore-record-fact.8": "Animals and the souls of other people are explicitly proposed for further experimentation.",
  "archive.lore-record-fact.9": "Digitization is connected to memory preservation and to converging data with information from the past through the Ley Lines.",
  "archive.lore-index-note.1": "SOURCE NOTE · All three items can be obtained from the Trounce Domain rewards of Binding Field of Universal Nirvana and combine into Anomalous Tree Marrow once the set is complete. Completing the set is also tied to the hidden achievement \"A Finality for the Anomalous\".",

  "archive.early-source-chip.1": "GROUP · EARLY ZANDIK RECORDS",
  "archive.early-source-chip.2": "SOURCE · SUMERU FIELD RECORDS",
  "archive.early-source-chip.3": "VERSION 3.0",
  "archive.early-source-chip.4": "ARDRAVI VALLEY",
  "archive.early-record-code.1": "RECORD · ZND-01",
  "archive.early-title.1": "Akademiya Investigation Team's Interim Report",
  "archive.early-summary.1": "An early Akademiya field report signed by \"Trainee Dastur, Zandik\", introducing his name through research into ancient machines and the Schwanenritter.",
  "archive.early-tag.1": "Zandik",
  "archive.early-tag.2": "Akademiya",
  "archive.early-tag.3": "Ancient Machines",
  "archive.early-label.note": "ARCHIVE NOTE",
  "archive.early-note.1": "One of the earliest records connected to Zandik. The surviving fragments document an Akademiya investigation of giant mechanisms related to earlier finds at Gurabad. The report closes with Zandik identifying himself as the recorder and a trainee Dastur.",
  "archive.early-label.data": "KEY DATA",
  "archive.early-fact.1": "The document explicitly names Zandik as a trainee Dastur of the Akademiya.",
  "archive.early-fact.2": "He compares the mechanisms with previously studied \"Gurabad samples\" and considers whether their automatic systems could be restored.",
  "archive.early-fact.3": "The report also records the discovery of the Schwanenritter and links them with the legends of the Ruins of Dahri.",
  "archive.early-record-code.2": "RECORD · ZND-02",
  "archive.early-title.2": "Zandik's Note · Devantaka Mountain",
  "archive.early-summary.2": "A hidden research note inside the Ruin Golem showing Zandik privately studying its components, construction, and manufacturing principles.",
  "archive.early-tag.4": "Ruin Golem",
  "archive.early-tag.5": "Reverse Engineering",
  "archive.early-tag.6": "Secrecy",
  "archive.early-note.2": "The note was hidden inside the giant machine at Devantaka Mountain. Zandik records his fascination with its spare components and intends to dismantle and document them in detail. He also makes clear that this private investigation must remain concealed from the rest of the expedition.",
  "archive.early-fact.4": "Zandik is interested not merely in operating the machine, but in understanding how its components were manufactured.",
  "archive.early-fact.5": "He distinguishes the mechanism's craftsmanship from artifacts produced by civilizations under the rule of the Archons.",
  "archive.early-fact.6": "He deliberately keeps the investigation secret from the other members of the research team.",
  "archive.early-record-code.3": "RECORD · ZND-03",
  "archive.early-title.3": "Sumeru Investigation Team's Note",
  "archive.early-summary.3": "A surviving expedition record describing Zandik stopping a dangerous machine and then arguing that it should be taken back to the Akademiya for disassembly and reverse engineering.",
  "archive.early-tag.7": "Expedition",
  "archive.early-tag.8": "Reverse Engineering",
  "archive.early-tag.9": "Academic Conflict",
  "archive.early-note.3": "The surviving fragments credit Zandik's quick reaction with preventing a greater disaster during the expedition. Once the machine was stopped, however, his insistence on transporting it to the Akademiya for disassembly, reverse engineering, and testing was condemned by the supervising scholar.",
  "archive.early-fact.7": "The team acknowledges that Zandik reacted quickly enough to prevent a more serious incident.",
  "archive.early-fact.8": "He argues for bringing the machine back to the Akademiya to study it through disassembly and reverse engineering.",
  "archive.early-fact.9": "Sage Sharnama reprimands him and removes his authorship credit from the expedition research.",
  "archive.early-source-note.1": "SOURCE NOTE · These records belong to the cluster of early Zandik material introduced with Sumeru in Version 3.0. Together they establish his Akademiya status, his interest in ancient machinery, and the recurring conflict between his research methods and academic authority.",
  "archive.p.4": "The first major official appearance of Dottore's modern design among the Harbingers.",
  "archive.span.1": "Official source",
  "archive.p.5": "Official Version 3.1 trailer featuring Dottore, Nahida, and Scaramouche.",
  "archive.span.2": "Official source",
  "archive.p.6": "Official material for the Sumeru climax and the artificial-god project.",
  "archive.span.3": "Official source",
  "archive.p.7": "A later official trailer covering a new stage of Dottore's story in Nod-Krai.",
  "archive.span.4": "Official source",
  "archive.p.8": "Official trailer for the later storyline, again crediting Dottore among the voiced characters.",
  "archive.span.5": "Official source",
  "archive.p.9": "HoYoLAB's official database for cross-checking records, characters, items, and in-game material.",
  "archive.archive-source-note.1": "ARCHIVE NOTE · External material remains with its respective rights holders. The site stores only links and interface previews; an internet connection is required.",
  "audio.tag.1": "OFFICIAL REMOTE SOURCE",
  "audio.audio-intro.1": "Instead of local audio files, this section uses official Genshin Impact videos as audiovisual records. Select an entry on the right: the source loads through the embedded player, and the original can always be opened separately.",
  "audio.span.1": "Open official source ↗",
  "audio.audio-online-note.1": "The embedded player and previews require an internet connection. If the browser blocks playback from a local HTML file, use the \"Open official source\" link.",
  "ui.credit-label.1": "ARCHIVE MAINTAINER",
  "ui.credit-note.1": "A non-commercial fan archive. Genshin Impact and related materials belong to HoYoverse. This project was created to organize official materials and character analysis.",
  "ui.author-site.1": "Personal site ↗",
  "ui.site-pending.1": "Personal site · link will be added later",
  "footer.span.1": "SUBJECT II ARCHIVE · FINAL 04 · LORE EXPANSION",
  "aria.closeMenu": "Close menu"
};
